/**
 * Generates ATTRIBUTIONS.md (docs/14 §9) by reusing the ONE attribution
 * formatter (CLAUDE.md R3). One section per locale, one line per third-party
 * quote (`rights: quoted-with-attribution`), sorted by work/text.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { attributionMarkdown } from '../src/features/quote/attribution';
import type { QuoteRecord } from '../src/features/quote/types';

interface Idx {
  locales: { code: string; file: string }[];
}
interface QFile {
  quotes: QuoteRecord[];
}

const dataDir = join(process.cwd(), 'data');
const idx = JSON.parse(readFileSync(join(dataDir, 'quotes/index.json'), 'utf8')) as Idx;

const lines: string[] = [
  '<!-- generated by scripts/gen-attributions.ts — do not edit -->',
  '',
  '# Attributions',
  '',
  'Third-party lines included as short, attributed quotations; rights remain their',
  "owners'. Removal requests: see the takedown policy (README / DISCLAIMER).",
  '',
];

let count = 0;
for (const loc of idx.locales) {
  const file = JSON.parse(readFileSync(join(dataDir, `quotes/${loc.file}`), 'utf8')) as QFile;
  const thirdParty = file.quotes
    .filter((q) => q.attribution.rights === 'quoted-with-attribution')
    .sort((a, b) => (a.attribution.work ?? a.text).localeCompare(b.attribution.work ?? b.text));
  if (thirdParty.length === 0) continue;
  lines.push(`## ${loc.code}`, '');
  for (const q of thirdParty) {
    lines.push(`- ${attributionMarkdown(q)}`);
    count += 1;
  }
  lines.push('');
}
if (count === 0) lines.push('_No third-party attributed quotes yet._', '');

const target = join(process.cwd(), 'ATTRIBUTIONS.md');
writeFileSync(target, lines.join('\n'), 'utf8');
console.log(`gen:attributions — ${count} entr${count === 1 ? 'y' : 'ies'} → ${target}`);
